# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20170315_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(default='motion', max_length=255, verbose_name='Sensor type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='color',
            field=models.CharField(default='green', max_length=255, verbose_name='Zone color'),
            preserve_default=False,
        ),
    ]
