# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
